### PR TITLE
Breaking change: code update to Vite 5

### LINKED ISSUE #11: Receiving warning of deprecated options in this html-plugin
Hello,

I'm receiving these warnings when I run the dev server on **Vite** with your **vite-plugin-html-config** plugin:

> plugin 'html-plugin' uses deprecated 'enforce' option. Use 'order' option instead.
> plugin 'html-plugin' uses deprecated 'transform' option. Use 'handler' option instead.

### PR DESCRIPTION
**Pull request by HansDP**
This change introduces a breaking change, hence the version change in package.json

This closes #11

### CODE REVIEW

**Comment by ahwgs** [comment]
Need to consider compatibility with older versions

**Comment by urakozz** [comment]
@ahwgs Compatibility could be achieved by versioning. Say v2 for the Vite >= 5

**Comment by urakozz** [comment]
@ahwgs hello, could you publish new version to the NPM please?

**Comment by MikeLacroix** [comment]
Well, I guess this repository is dead...

**Comment by jervalles** [comment]
Hello, possible to public on NPM please?

**Comment by ahwgs** [comment]
@jervalles @MikeLacroix @urakozz  
I'm very sorry for not responding in a timely manner
The latest version has been released

**Comment by jervalles** [comment]
@ahwgs thank you so much, it's all good now

**Pull request merged**
